version: "3.8"

services:
  app:
    container_name: vite-react-app
    image: react_project:latest
    build:
      context: .
    ports:
      - 3000:5173
    volumes:
      - appdata:/app/mount/node_modules
      - './mount:/app'

volumes:
  appdata:
    labels:
      - "com.description: React App Data Volume"
